name: main

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código fonte
      uses: actions/checkout@v2
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with: 
        username: ${{ secrets.DOCKER_USER}}
        password: ${{ secrets.DOCKER_PASS}}
        
    - name: Construir imagem Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: lipeoliveira94/somativa2:latest

  teste:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - run: python3 app.py
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "python"
    
    #- name: sast-scan
     # uses: AppThreat/sast-scan-action@1.0.2
  
    #- name: Teste de segurança utilizando OWASP ZAP
     # uses: owasp/zap-full-scan@v1
      #with:
       # target: http://localhost:8080
        #reportFilename: zap-report.html
        #reportTitle: OWASP ZAP Report

  deploy:
    runs-on: ubuntu-latest
    needs: teste
    steps:
    - name: ngrok-tunnel
      uses: vmactions/ngrok-tunnel@v0.0.1
      with:
        protocol: http   
        port: 5000
        
    #- name: Implantação utilizando Ngrok
     # uses: w9jds/ngrok-action@v1
      #with:
       # authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}
        #region: us
        #port: 8080
